#cloud-config
package_update: true
apt:
  sources:
    100-ubnt-unifi.list:
      source: "deb https://www.ui.com/downloads/unifi/debian stable ubiquiti"
      keyid: 06E85760C0A52C50
packages:
  - apt-transport-https
  - openjdk-8-jre-headless
  - unifi